### ISSUE TITLE
Cannot fire up e2e.openWindow

### ISSUE THREAD

**Issue by eavichay** [inf3rno/e2e#138]
**package version: 0.1.2**

error:
```text
> node test-runner.js

/Users/eavichay/dev/showroom/node_modules/@inf3rno/e2e/lib/Browser.js:22
                throw error;
                ^

TypeError: global.open is not a function
    at Object.openWindow (/Users/eavichay/dev/showroom/node_modules/@inf3rno/e2e/lib/Browser.js:14:35)
    at Object.<anonymous> (/Users/eavichay/dev/showroom/test-runner.js:7:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
npm ERR! Test failed.  See above for more details.
```

test-runner.js
```javascript
const e2e = require('@inf3rno/e2e');
const target = 'http://localhost:8080';
const navigator = e2e.openWindow(target); // also doesn't work without arguments
```

Help?

**Comment by inf3rno** [comment]
It means that `window.open` is not allowed. Probably it is a popup blocker.

**Comment by inf3rno** [comment]
Note that the current readme is not written for the v0.1.2 release. It was modified since then. The readme of that release is this: https://github.com/inf3rno/e2e/tree/v0.1.2 Still this should not happen. I never experienced a problem like this, so without knowing how to reproduce it, it is hard to fix it...

**Comment by eavichay** [comment]
@inf3rno Sorry, still does not work. :(

**Comment by inf3rno** [comment]
Ohh now that I read it again. You did `node test-runner.js`. It is not how this lib works, your test code should run in browser, not in node. Currently only latest Chrome is supported. Check the current code, mainly the `karma.conf.js`, the `test.sh` and the `test` directory and read Karma documentation if you are not familiar with that. https://karma-runner.github.io/latest/index.html

**Comment by inf3rno** [comment]
Interesting issue though. I think I should add a proper error message for these cases.

**Comment by eavichay** [comment]
@inf3rno Ok, then. Should I simply run karma instead?

What I am trying to do, is run unit-tests of components on an EXISTING web page that has it's own functionality. Very similar to how E2E runs, only the test execution must be in the browser.

**Comment by inf3rno** [comment]
What e2e does is visiting a website in a new window and following links, sending forms, clicking buttons, etc. It is close to automated browsing, it is something similar to what selenium does, but it is pure javascript, so you can use your favourite js test frameworks with it. It is good for end to end testing a webapplication, so even the GUI and the database queries are tested with it, but it does not cover as much as unit tests. It is good if you want to make sure that the GUI works as expected too, or if you don't want to write unit tests, but still you want some automated tests to check your webapplication.

If you want to unit test your client side javascript code, then use karma instead. You'll need a bundle creator, probably browserify or webpack and a testing framework like mocha or jest too. Have fun! :-)

**Comment by eavichay** [comment]
@inf3rno Well then, I got it all wrong. I thought your tool executes e2e tests by injecting the test code into the tested webpage.

Actually that is *exactly* what I need. I have a fully-functional web page and I need to execute javascript tests from the browser (no selenium or any browser driver).

I have tried working with karma by modifying the customClientPage but it's still not there...

**Comment by inf3rno** [comment]
@eavichay 
> I thought your tool executes e2e tests by injecting the test code into the tested webpage.
Maybe I misunderstood then. Sure you can do that with this lib, but be aware that it is not production ready and that the Chrome devs might kill it later by no longer supporting the security disabling CLI flags I currently use.
